export default [
  {
    id: 1,
    title: 'Randonnée nocturne à Wanaka',
    author: 'Manu Macron',
    category: 'Sport',
    date: '24 septembre 2021',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam minus veniam delectus molestias repellendus nesciunt debitis sed laudantium explicabo aut, dolorum fuga laborum accusamus repudiandae consequuntur ipsum nulla sint sapiente.',
  },
  {
    id: 2,
    title: 'Plongée à Melbourne',
    author: 'Donald Trump',
    category: 'Sport',
    date: '28 septembre 2021',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam minus veniam delectus molestias repellendus nesciunt debitis sed laudantium explicabo aut, dolorum fuga laborum accusamus repudiandae consequuntur ipsum nulla sint sapiente.',
  },
  {
    id: 3,
    title: 'Randonnée equestre à New York',
    author: 'Eva Smith',
    category: 'Sport',
    date: '12 octobre 2021',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam minus veniam delectus molestias repellendus nesciunt debitis sed laudantium explicabo aut, dolorum fuga laborum accusamus repudiandae consequuntur ipsum nulla sint sapiente.',
  },
  {
    id: 4,
    title: 'Visite musée',
    author: 'Paulo Figuero',
    category: 'Culture',
    date: '18 octobre 2021',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam minus veniam delectus molestias repellendus nesciunt debitis sed laudantium explicabo aut, dolorum fuga laborum accusamus repudiandae consequuntur ipsum nulla sint sapiente.',
  },
  {
    id: 5,
    title: 'Tournée des bars à Paris',
    author: 'Paul Martin',
    category: 'Party',
    date: '14 novembre 2021',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam minus veniam delectus molestias repellendus nesciunt debitis sed laudantium explicabo aut, dolorum fuga laborum accusamus repudiandae consequuntur ipsum nulla sint sapiente.',
  },
  {
    id: 6,
    title: 'Partie de curling',
    author: 'Jhon McCain',
    category: 'Sport',
    date: '06 juin 2021',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam minus veniam delectus molestias repellendus nesciunt debitis sed laudantium explicabo aut, dolorum fuga laborum accusamus repudiandae consequuntur ipsum nulla sint sapiente.',
  },
  {
    id: 7,
    title: 'Partie de curling',
    author: 'Jhon McCain',
    category: 'Sport',
    date: '06 juin 2021',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam minus veniam delectus molestias repellendus nesciunt debitis sed laudantium explicabo aut, dolorum fuga laborum accusamus repudiandae consequuntur ipsum nulla sint sapiente.',
  },
  {
    id: 8,
    title: 'Restaurant chinois',
    author: 'Brigite Bardot',
    category: 'Sport',
    date: '06 juin 2021',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam minus veniam delectus molestias repellendus nesciunt debitis sed laudantium explicabo aut, dolorum fuga laborum accusamus repudiandae consequuntur ipsum nulla sint sapiente.',
  },
  {
    id: 9,
    title: 'Partie de curling',
    author: 'Jacques Chirac',
    category: 'Sport',
    date: '06 juin 2021',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam minus veniam delectus molestias repellendus nesciunt debitis sed laudantium explicabo aut, dolorum fuga laborum accusamus repudiandae consequuntur ipsum nulla sint sapiente.',
  },
];
